url: "http://www.wizdigital.com" # the base hostname & protocol for your site
# baseurl: "/wizdigital-jekyll-blog/" # the subpath of your site, e.g. /blog/

# Site settings
title: "wizDigital 为知数"
email: us@wizdigital.com
description: "数字整合营销"
twitter_username: jekyllrb
github_username:  jekyll

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ef5431

# Build settings
markdown: kramdown
permalink: pretty

include:
  - .nojekyll

exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"
  - "Rakefile"

# Team names, titles and social links
people:
- name: Ben Zhang
  pic: ben.zhang
  position: Lead Designer
  social:
    - title: weibo
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: #

- name: Joey Jiao
  pic: joey.jiao
  position: Lead Marketer
  social:
    - title: weibo
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Jenny Qian
  pic: jenny.qian
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: github
      url: #

# - name: Nancy Tang
#   pic: nancy.tang
#   position: Lead Strategy
#   social:
#     - title: weibo
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #
  - title: wechat
    url: #
  - title: weibo 
    url: #
  - title: linkedin
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210
